### ISSUE TITLE
Masking meteors, hover help

### ISSUE THREAD

**Issue by jazdown** [jazdown/dsn1676-term-project#1]
The meteors in the "apocalypse" scene extend down too far from the scene and translations seem not to help anything. Also, the intended transition from the "normal" scene to the "apocalypse" scene is just hovering over the banner, but it flickers and will only show all the content steadily when you click and hold on the banner. 
Thanks in advance!
@thomasjbradley

![screen shot 2015-02-03 at 1 47 35 am](https://cloud.githubusercontent.com/assets/6373208/6015754/bc985eba-ab46-11e4-82ca-50d891a5035b.png)
![screen shot 2015-02-03 at 1 48 04 am](https://cloud.githubusercontent.com/assets/6373208/6015753/bc96d3d8-ab46-11e4-9572-dc3feff59e4a.png)

**Comment by jazdown** [comment]
Update: changed hover fading to automatically fade to evil scene. Still need help with meteors showing through below scene area.

**Comment by thomasjbradley** [comment]
Try adding `overflow: hidden` onto your evil scene. That should chop off the meteors at the bottom.
