### ISSUE TITLE
Nostradamus turned blue..?

### ISSUE THREAD

**Issue by jazdown** [jazdown/dsn1676-term-project#2]
@thomasjbradley

My SVG from illustrator is coloured well and uses hex colours, and when I saved it and cleaned it up in SVGOMG, the colours completely shifted once it was used in my code. What's wrong?
THIS is in Illustrator:
![screen shot 2015-04-06 at 11 12 06 pm](https://cloud.githubusercontent.com/assets/6373208/7016465/bd21f498-dcb2-11e4-98b2-2a01060c3e6c.png)

THIS is in my Firefox preview....
![screen shot 2015-04-06 at 11 12 18 pm](https://cloud.githubusercontent.com/assets/6373208/7016467/cf486d5a-dcb2-11e4-8c0a-58f49e6a5dc9.png)

**Comment by thomasjbradley** [comment]
Do you have multiple SVGs embedded on the page?

**Comment by jazdown** [comment]
Yes, this is the third svg... is that not allowed? 
The first one I used was waves at the bottom:
![screen shot 2015-04-07 at 12 16 52 pm](https://cloud.githubusercontent.com/assets/6373208/7027869/1437e964-dd20-11e4-8b45-c5a92ec70a60.png)
Then Nostradamus and a book:
![screen shot 2015-04-07 at 1 30 22 am](https://cloud.githubusercontent.com/assets/6373208/7027873/1d0ee240-dd20-11e4-961c-17eb5fcd5462.png)

**Comment by thomasjbradley** [comment]
It's possible, but there's a collision with the classes. Illustrator is re-using classes, here:
https://github.com/jazdown/dsn1676-term-project/blob/gh-pages/index.html#L72

And here:
https://github.com/jazdown/dsn1676-term-project/blob/gh-pages/index.html#L532

And here:
https://github.com/jazdown/dsn1676-term-project/blob/gh-pages/index.html#L577

So, the CSS is being overwritten.

**Comment by jazdown** [comment]
Ohh okay. Can I do anything to change the style bits?

**Comment by thomasjbradley** [comment]
Yeah, just go through the SVGs and change their classes to something unique for each of them.
